### ISSUE TITLE
Add Support for nextcloud 24

### ISSUE THREAD

**Issue by jakobroehrl** [JonathanTreffler/sharerenamer#115]
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by JonathanTreffler** [comment]
Nextcloud 24 got released, i will test compatibility once the docker image for version 24 is available.

**Comment by JonathanTreffler** [comment]
The linuxserver nextcloud docker can already handle Nextcloud 24 unlike the official one.

I have just tested it on Nextcloud 24 using it.
It works fine. I will release a new version with Nextcloud 24 enabled.

Depending on your timezone this could still be a day 1 release :wink:

**Comment by JonathanTreffler** [comment]
The release 3.0.1 is tested, built, signed and uploaded to the appstore.
It will be available as an update in the nextcloud app store soon.

**Comment by jakobroehrl** [comment]
Thanks a lot for your work!
