### ISSUE TITLE
After creating a share link, Share Renamer requires a refresh to recognize it for renaming

### ISSUE THREAD

**Issue by melyux** [JonathanTreffler/sharerenamer#118]
If you open the sidebar and share a file, and then switch to the Share Renamer tab of the sidebar, it'll show up as blank until you refresh the page. Or go to another file and come back. It should ideally refresh its "knowledge" of the file's sharing status when the Share Renamer tab is switched to, instead of upon sidebar opening (which I assume is what's happening now).

**Comment by JonathanTreffler** [comment]
This is a known issue: https://github.com/JonathanTreffler/sharerenamer#known-issues
