### ISSUE TITLE
name already exist

### ISSUE THREAD

**Issue by overlaps1** [JonathanTreffler/sharerenamer#120]
Hi,

Any chance to cleanup token id database ? every time I try to rename a link ti says: a link share with that token already exist

**Comment by JonathanTreffler** [comment]
The token database is just the normal nextcloud one, if it says the token is already taken with every text as the token, the problem is not the token database.

**Comment by overlaps1** [comment]
thanks for your reply.
Any suggestion to point me in the right direction ?
I have been digging everywhere and no answer

**Comment by JonathanTreffler** [comment]
Please provide a screenshot or the exact text of the error message, error messages in the browser dev tools console, nextcloud version, app version and relevant nextcloud logs.

**Comment by overlaps1** [comment]
![image](https://user-images.githubusercontent.com/104126430/164394857-759eaa7b-f192-412a-a96c-fd089badf92c.png)

[Nextcloud Hub II] (23.0.3)
ShareRenamer 3.0.0

there is nothing in the log that could be relevant. tried a tail -f but nothing shows up when trying to rename a link. nothing is logged

**Comment by JonathanTreffler** [comment]
I will look into it later when i have time.

(with the nextcloud log i meant in the logging section in the admin settings).

Please also post the status code and response from the rename network request in the network section of the dev tools.

Please remind me if i forget to get back to you with a solution 🙂.

**Comment by overlaps1** [comment]
thnaks for helping,

I am not sure what you mean -> (with the nextcloud log i meant in the logging section in the admin settings)

**Comment by overlaps1** [comment]
Hi Jonathan,

I am not sure what you mean :
(with the nextcloud log i meant in the logging section in the admin settings).
Please also post the status code and response from the rename network request in the network section of the dev tools.

I'll be glad to give all the informations you need, can you be more precise ?

**Comment by overlaps1** [comment]
I f you mean network section of chrome dev tools, here is the output:

<html><body>
<span class="message-body-wrapper"><span class="message-flex-body"><span class="message-body devtools-monospace"><span class="xhr"></span><span class="method">POST</span><span class="url" title="https://portail.eec31.com/apps/sharerenamer/rename">https://portail.eec31.com/apps/sharerenamer/rename</span><a class="status"><span class="status-info">[HTTP/1.1 <span class="status-code" data-code="409" title="En savoir plus">409</span> Conflict 40ms]</span></a></span> </span><div class="network-info network-monitor"><div class="devtools-sidebar-tabs"><div class="tabs "><nav class="tabs-navigation"><ul class="tabs-menu" role="tablist"><li class="tabs-menu-item panel-with-code is-active" role="presentation"><span class="devtools-tab-line"></span></li></ul></nav></div></div></div></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><span class="devtools-tab-line"></span></span><span class="message-body-wrapper"><div id="headers-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="headers-tab"><div class="tab-panel panel-with-code"><div class="headers-panel-container"><div class="devtools-toolbar devtools-input-toolbar"><div class="devtools-searchbox"><input class="devtools-filterinput" placeholder="Filtrer les en-têtes" type="search" value=""></div></div><div class="panel-container"><div class="headers-overview"><div class="url-preview"><div class="properties-view"><div class="tree-container">

  |  
-- | --
POST | https://portail.eec31.com/apps/sharerenamer/rename

</span>
</body>
</html>POSThttps://portail.eec31.com/apps/sharerenamer/rename
[[HTTP/1.1 409 Conflict 40ms]]()

	
POST
	https://portail.eec31.com//apps/sharerenamer/rename
État
409
Conflict
VersionHTTP/1.1
Transfert1,08 Ko (taille 8 o)
Politique de référentno-referrer

	
Cache-Control
	no-cache, no-store, must-revalidate
Connection
	Keep-Alive
Content-Length
	8
Content-Security-Policy
	default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
Content-Type
	application/json; charset=utf-8
Date
	Fri, 22 Apr 2022 09:45:10 GMT
Expires
	Thu, 19 Nov 1981 08:52:00 GMT
Feature-Policy
	accelerometer 'none'; autoplay 'self'; geolocation 'none'; midi 'none'; notifications 'self'; push 'self'; sync-xhr 'self' https://portail.eec31.com/; microphone 'self'; camera 'self'; magnetometer 'none'; gyroscope 'none'; speaker 'self'; vibrate 'self'; fullscreen 'self'; payment 'none'; usb 'none'
Feature-Policy
	autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
Keep-Alive
	timeout=5, max=97
Pragma
	no-cache
Referrer-Policy
	no-referrer
Server
	Apache
Strict-Transport-Security
	max-age=15768000; preload
X-Content-Type-Options
	nosniff
X-Download-Options
	noopen
X-Frame-Options
	SAMEORIGIN
X-Permitted-Cross-Domain-Policies
	none
X-Robots-Tag
	none
X-XSS-Protection
	1; mode=block
	
Accept
	application/json, text/plain, */*
Accept-Encoding
	gzip, deflate, br
Accept-Language
	fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Connection
	keep-alive
Content-Length
	61
Content-Type
	application/json
Cookie
	__Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; oc4se3nuqamv=0rvamb8qshhnu0f70tuq3n159v; oc_sessionPassphrase=7fG%2FHjXJESGurWtDauncYbc4cTjFZpoXkbvWZUK6Oe9S4xCsLWx1RIM4QDx%2FKImo1Iin5%2Bpv8X9XeDLFNST%2BUCCKfxbhw3nMgS3q2KY8y%2BhE%2BqLLlDUn3z9GykVDmNpc; nc_username=sam; nc_token=g1CyyAKraZVDpDae1Q3JbxDAvD%2FrxN%2FA; nc_session_id=0rvamb8qshhnu0f70tuq3n159v
DNT
	1
Host
	portail.eec31.com
Origin
	https://portail.eec31.com
requesttoken
	7+6jMqZpVVpSaKZAoYz9u+hRv3A//hX+idODsjdwCRs=:26CMHfAFMDE2P+F1mcTJyYdj9l92iH7V6qbW1Q47byI=
Sec-Fetch-Dest
	empty
Sec-Fetch-Mode
	cors
Sec-Fetch-Site
	same-origin
User-Agent
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0

**Comment by JonathanTreffler** [comment]
Since this issue doesn't contain all the information of your forum post i will cite it here for context.

> Hi everybody,
> 
> I have been using share renamer to customize links.
> Since I had to migrate the server with new lan IP and hostname, I lost all the sharing links.
> Now trying to recreate the links again, it says name already exist.
> I restored nextcloud database but it didn’t make the job
> Is there a way to cleanup links database or remove all old created token id ?
> Thanks

**Comment by JonathanTreffler** [comment]
I have looked into it: I don't see any error in the code of this app.
Your database table containing the share links must have gotten messed up by the migration.
My current recommendation is to **backup** and clean the entire "oc_share" table of your database using
```sql
DELETE FROM `oc_share` WHERE share_type=3;
```

:warning: That will remove any files shared via a link (the share_type=3 prevents other kinds of shares from being deleted). :warning:

After that you can recreate all the share links.

**Comment by overlaps1** [comment]
Hi Jonathan,
Thanks dor paying attention to this issue.
Your command did the trick, thanks
