### ISSUE TITLE
Nextcloud 26 compatibility 

### ISSUE THREAD

**Issue by elpraga** [JonathanTreffler/sharerenamer#220]
Thank you @JonathanTreffler for this great and useful app!

Would it be possible to make it compatible with the new Nextcloud 26 (Hub 4). 

In my case, it is one of the apps that keeps me from upgrading.

**Comment by JonathanTreffler** [comment]
I will look into it. It will probably just require a bump of the maximum compatible version value.

**Comment by JonathanTreffler** [comment]
I just released v3.2.0 with support for Nextcloud 26 :)
