### ISSUE TITLE
NextCloud v28

### ISSUE THREAD

**Issue by wildernessfamily** [JonathanTreffler/sharerenamer#270]
I just setup NextCloud for a new project. I always install Sharerenamer for all my NextCloud instances. However, in NC v28.0.2 when I enable the extension, go to a folder, share it, the Sharerenamer icon does not show. There is no way to create a new share link.

**Comment by erwdavid** [comment]
Same for me, and I get following errors in log : 

[sharerenamer] Fatal: Error during app loading: Autoload path not allowed: /usr/local/nextcloud/apps/sharerenamer/appinfo/application.php
	GET /apps/logreader/api/log?offset=0&query=
	de 80.74.64.33 par erwan à 2024-03-29T14:44:49+00:00

**Comment by mvosz** [comment]
same

**Comment by JonathanTreffler** [comment]
I just released [v3.3.0](https://github.com/JonathanTreffler/sharerenamer/releases/tag/v3.3.0) of this app, that adds support for Nextcloud 29 :partying_face: 

If you install it manually and override the version check in the info.xml it is likely to work on versions 26 through 28 also, but I will not go through the trouble of checking all these old version for compatibility.

It took very little work to get this app compatible with modern versions of nextcloud, just the bootstrap logic, but it has sadly taken this long for me to get around to it. There are always just more nextcloud apps to update, than I have the time for :/

This app in general needs a lot more work, but I cannot promise I will find the time for that soon, but I will try. At least it works now like it used to work on the old versions.

**Comment by Quix0r** [comment]
Please remember that this app won't update if you update NC28 -> 29 as you get an error shown in my report by doing so. To fix this issue, you need to manually update it by downloading the app's ZIP file and unzip it in proper folder + `chmod 06xx` on files and `chmod 07xx` on directories.

**Comment by Quix0r** [comment]
https://github.com/JonathanTreffler/sharerenamer/releases/download/v3.3.0/sharerenamer.tar.gz claims to be 3.2.0 release (NC26 max, but also 28.0.5 did work). Can you please double-check if you have uploaded proper bundle?

**Comment by JonathanTreffler** [comment]
> https://github.com/JonathanTreffler/sharerenamer/releases/download/v3.3.0/sharerenamer.tar.gz claims to be 3.2.0 release (NC26 max, but also 28.0.5 did work). Can you please double-check if you have uploaded proper bundle?
> 
> EDIT: `ChangeLog.md` states 3.2.0 and the app isn't working with NC29. `info.xml` says 3.3.0 however.

The bundle is correct and get's parsed by the nextclpoud app store, which correctly shows 3.3.0 for Nextcloud 29:
![grafik](https://github.com/JonathanTreffler/sharerenamer/assets/28999431/282a7258-5edc-48be-adf1-2ca23569dd2a)

You are correct however, that my edit of the Changelog did not make it into the bundle, I must have forgot to git pull one last time, but that is inconsequential to the install of the app.

**Comment by Quix0r** [comment]
That's odd. Then why I still got this error? Please refer to this issue: https://github.com/nextcloud/server/issues/45099

**Comment by JonathanTreffler** [comment]
I am currently updating all dependencies, which I think will likely fix the problem and will create a .1 release.

**Comment by Quix0r** [comment]
Unfortunately not. :cry:  I had to remove your `sharerenamer/vendor/` directory, then it works.

**Comment by JonathanTreffler** [comment]
Shipping with the vendor directory is valid for nextcloud apps and should not cause issues.
But since this app has no composer dependencies, only dev dependencies I could leave composer out of the app bundle altogether. I just included it out of habit, because more complex nextcloud apps need it. I will look into it.

**Comment by daffydock** [comment]
Hmmm, so unlike @Quix0r, who deleted the `/sharerenamer/vendor/ folder`, can I get away with it by just deleting the `composer` folder until you release an update? 

Cheers

**Comment by JonathanTreffler** [comment]
the composer folder is the vendor folder.

**Comment by daffydock** [comment]
Oh, I see. The reason I am asking is because on my install, I have both, a `sharerename/vendor` and a `sharerenamer/vendor/composer` folder. Unless I know better, it seems that you talking about a different folder since the it sounds like you are both speaking about different folders altogether. Perhaps there is an overlap in naming that I am simply not aware of. 

As such, I could have deleted the `sharerenamer/vendor/*composer* `folder but still have root *Vendor* folder within `apps/harerenanmber`. If I delete the *Vendor,* folder it would delete the *Composer* folder along 12 others within it, along a file within it it. 

To confirm, I can delete `sharerename/vendor` and all the other folders within it? Or just the *Composer* folder found within the Vendor folder? 

If anything and in either way, I am learning something new, thank you.

**Comment by JonathanTreffler** [comment]
If the app works delete nothing. If it doesnt try deleting the whole vendor folder.

**Comment by daffydock** [comment]
> If the app works delete nothing. If it doesnt try deleting the whole vendor folder.

It does not work well, errors get spammed in the log on NC29. Will test by delete it. Again, thank you for your feedback.

**Comment by livier** [comment]
Not working here, Nextcloud 29.0.0, sharerenamer 3.3.1
I do not see anything from sharenamer in the UI
Log entry, if relevant : 
	[sharerenamer] Fatal: Error during app service registration: Failed opening required '/var/www/vhosts/mycloud.mydomain.tld/httpdocs/nextcloud/apps/sharerenamer/lib/AppInfo/../../vendor/autoload.php' (include_path='/var/www/vhosts/mycloud.mydomain.tld/httpdocs/nextcloud/3rdparty/pear/archive_tar:/var/www/vhosts/mycloud.mydomain.tld/httpdocs/nextcloud/3rdparty/pear/console_getopt:/var/www/vhosts/mycloud.mydomain.tld/httpdocs/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/vhosts/mycloud.mydomain.tld/httpdocs/nextcloud/3rdparty/pear/pear_exception:/var/www/vhosts/mycloud.mydomain.tld/httpdocs/nextcloud/apps')
	GET /index.php/apps/logreader/api/poll?lastReqId=Zk6EQSUOs9mJcqr37NK41AAAAEU
	de 109.231.82.116 par -- à 22 mai 2024, 19:48:27

**Comment by JonathanTreffler** [comment]
If you are having issues on Nextcloud 28 or 29 check again with version https://github.com/JonathanTreffler/sharerenamer/releases/tag/v3.4.0 I just released, which is a complete refactor of the codebase :)

**Comment by livier** [comment]
Thanks, that's good

**Comment by livier** [comment]
not so good unfortunatly ... 
I can rename a link, and when I try to open it, page shows : 

Ce répertoire est indisponible, merci de consulter les journaux ou de contacter votre administrateur

and the log says : 

[sharerenamer] Fatal: Error during app service registration: Failed opening required '/var/www/vhosts/mycloud.mydomain.tld/httpdocs/nextcloud/apps/sharerenamer/lib/AppInfo/../../vendor/autoload.php' (include_path='/var/www/vhosts/mycloud.mydomain.tld/httpdocs/nextcloud/3rdparty/pear/archive_tar:/var/www/vhosts/mycloud.mydomain.tld/httpdocs/nextcloud/3rdparty/pear/console_getopt:/var/www/vhosts/mycloud.mydomain.tld/httpdocs/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/vhosts/mycloud.mydomain.tld/httpdocs/nextcloud/3rdparty/pear/pear_exception:/var/www/vhosts/mycloud.mydomain.tld/httpdocs/nextcloud/apps')
	GET /ocs/v2.php/core/navigation/apps?format=json
	de 109.231.82.116 par -- à 23 mai 2024, 06:29:05

**Comment by livier** [comment]
I desactivated many other apps, and it does not changed anything.
The web page show the above error, but the link to download the zip file (for a folder) worked.
Trying to remove the "-" in the renamer, and it worked. A few month ago, with another instance of nextcloud, that was correct. 
Hope that report will help in anything ;-)

**Comment by ethernet-zero** [comment]
> If you are having issues on Nextcloud 28 or 29 check again with version [3.4.0](https://github.com/JonathanTreffler/sharerenamer/releases/tag/v3.4.0) I just released, which is a complete refactor of the codebase :)

Note that all versions starting with 3.3.0 are listed in the app store as requiring Nextcloud 29 and up, so you can't install it in Nextcloud 28 like in my case:

<img width="833" alt="Captura de pantalla 2024-07-11 a las 18 53 01" src="https://github.com/JonathanTreffler/sharerenamer/assets/295227/2d8da21d-80e6-41a6-ac3c-d9b907e72b20">

Is there a reason why Nextcloud 28 is left out?
