### ISSUE TITLE
Not longer maintained/looking for maintainers

### ISSUE THREAD

**Issue by DecaTec** [JonathanTreffler/sharerenamer#29]
Sadly, I cannot maintain this app any further.

The app is only compatible up to Nextcloud 17. It will probably need some changes in the Nextcloud core code in order to make it compatible to Nextloud 18+.

Because I don't have the time to maintain this project any further, I'm looking for a new maintainer. If you're interested, please reply on this issue or contact me.

**Comment by JonathanTreffler** [comment]
> Because I don't have the time to maintain this project any further, I'm looking for a new maintainer. If you're interested, please reply on this issue or contact me.

I would be interested, 
but i cannot promise a quick development of the Nextcloud 18/19 compatibility.
I am currently working on a rewrite of nextcloud/news in vue and it takes a lot of my time.
But because i used this App before upgrading to v18 and still want to use it i would like to help / make it compatible with Nextcloud v19.
I guess it would be a few weeks until i have some time for this app.

**Comment by ei8fdb** [comment]
@DecaTec I hope you get someone to take over maintainer of this app. I use it regularly and was sad to see it wasn't available in NC19.

I'm afraid I don't have the code skills to help, but I am happy to help with testing and UI design if needed.

**Comment by stratege1401** [comment]
Unfortunatly, i havent got the dev skill needed !! Hope to see this one alive again.

**Comment by klocke-io** [comment]
@JonathanTreffler Is there any way to help you?

**Comment by Piescko** [comment]
Hey @JonathanTreffler is there any way to help you?

**Comment by JonathanTreffler** [comment]
> Hey @JonathanTreffler is there any way to help you?

I don't know yet, but i will let you know :)

**Comment by daschmidt1994** [comment]
Some news @JonathanTreffler ?

**Comment by JonathanTreffler** [comment]
I currently plan to start the development in 3 weeks. My schedule is absolutely full right now

**Comment by intervisionlord** [comment]
Hey guys, i'd like to help too, but my coding skills are vbery poor ;)) but i could translate some things to russian ;) let me know when maintaining of this app continues.

**Comment by n3storm** [comment]
I can help @JonathanTreffler

**Comment by JonathanTreffler** [comment]
> I can help @JonathanTreffler

I did start the rewrite in a PR, but so far only a few basics are done. I don't think i will change anything in the PHP Code, but if i need help i will reach out to you.

**Comment by JonathanTreffler** [comment]
> but i could translate some things to russian

You can help with the translation at: https://www.transifex.com/nextcloud/nextcloud/sharerenamer/
But i don't know yet how many translation strings need to be changed and therefore re-translated for the rewrite.

![image](https://user-images.githubusercontent.com/28999431/98674481-28e3a080-2359-11eb-9349-978644fdc59d.png)

**Comment by Mululu** [comment]
Wird noch daran gearbeitet oder kann man damit abschließen?

**Comment by DecaTec** [comment]
@JonathanTreffler Any news on this?

**Comment by JonathanTreffler** [comment]
I have my Abitur final exams (German equivalent to high school) in 2 weeks. In 2 months they are all done and i will have a ton of time 🙂.

**Comment by ei8fdb** [comment]
> I have my Abitur final exams (German equivalent to high school) in 2 weeks. In 2 months they are all done and i will have a ton of time 🙂.

Good luck! :)

**Comment by stratege1401** [comment]
Best of luck for your exam !!!

Pretty sure you'll have it with honors !!!

Le jeu. 29 avr. 2021 à 22:33, Bernard Tyers ***@***.***> a
écrit :

**Comment by clemone210** [comment]
Hello together,
any changes in the future that this will work with Nextcloud 21?
Would love the rename the shares again.

**Comment by DecaTec** [comment]
@JonathanTreffler Any news on development?

**Comment by JonathanTreffler** [comment]
The repository got transferred to my account, thanks @DecaTec

**Comment by DecaTec** [comment]
@JonathanTreffler Thanks a lot! 
If you need support later on (e.g. releasing the app in the NC app store), please feel free to contact me.

**Comment by JonathanTreffler** [comment]
Also, I moved this repository (and its forks) to a new git network, so it is longer marked as a fork of LazyShpee, which has been archived for ages.

**Comment by ei8fdb** [comment]
> @JonathanTreffler Thanks a lot!
> If you need support later on (e.g. releasing the app in the NC app store), please feel free to contact me.

Thanks for improving the app @DecaTec. I appreciate your work on it.
