### ISSUE TITLE
ShareRenamer 3.0.0 does not work on NC 23.0.0

### ISSUE THREAD

**Issue by 42ske** [JonathanTreffler/sharerenamer#87]
After renaming a Link neither the original Link nor the renamed one work. If I deactivate Shareramer the renamed Link is working.

That's a bit strange and it would be fine if you could have a look at it.

**Comment by 42ske** [comment]
Do you need further information?

**Comment by ahornblatt** [comment]
Same here, doesnt seem to work anymore

**Comment by JonathanTreffler** [comment]
Sorry for taking so long, I have been extremely busy since January. I will have more time after next Wednesday and I will try to fix it then.

**Comment by JonathanTreffler** [comment]
I have no idea why it doesn't work for you. I have just tested it on nextcloud 24 and it works flawlessly. It seems unrealistic, that it does work on 24, but not on older versions, which have previously worked. I am closing this for now.
This does not ssem like an error related to a nextcloud version.

**Comment by JonathanTreffler** [comment]
Just tested it on 23.0.4, works fine

**Comment by zerojay** [comment]
This no longer appears to work on Nextcloud 25.
